#!/bin/bash

root_path="/mnt/vstor/CSE_CSDS_VXC204/bxz297/ICICLE/AI4CI/AI4CI3/GPUModeling/Kernel_sampling"

python $root_path/sampling_controller.py --config_path $root_path/configs/collect/baddbmm.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/bmm.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/crossentropy.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/embedding.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/fillmask.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/gelu.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/layernorm.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/linear_final.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/linear1.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/linear2.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/linear3.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/linear4.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/RoPE.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/softmax.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/flash_atten.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/RMSlayernorm.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/res_add.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/firstStage_optimizer.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/middleStage_optimizer.yml --precision fp16 --parts "$1" --part "$2"
python $root_path/sampling_controller.py --config_path $root_path/configs/collect/lastStage_optimizer.yml --precision fp16 --parts "$1" --part "$2"