{
  "module_name": "target_functions",
  "kernel_name": "parallel_cross_entropy_128",
  "function_name": "parallel_cross_entropy_128",
  "columns_name": ['mp', 'b', 'l', 'F_dur(us)', 'B_dur(us)'],
  "targets": [['vocab_parallel_cross_entropy'], ['autograd::engine::evaluate_function: _VocabParallelCrossEntropyBackward']],
  "first_n_column": 3, 

  # mp, b, l
  "starts":[1, 2, 1024],
  "steps":[2, 4, 256],
  "ends":[16, 8, 4096],
  "operators":['mul', 'mul', 'add'],


  # mp [1 ~ 16]  mul 2, 6, 
  # b [2 ~ 8] mul 2, 3 
  # l [1024 ~ 5120] add 64, 64
  # 1,152 in total

  "warmup_shapes":[8, 8, 2048],

  "wait": 4,
  "warmup": 6,

  # must > 5, number of sample for get_profiler and for get_one and get_all to caculate the avrage time cost
  "active": 10,

  # for get_profiler and get_one
  # "shapes":[16, 16, 2048],
  "shapes":[8, 8, 2048],

  # run_function, get_profiler, get_one, get_all
  "run": "get_all"
}

# test command
# python sampling_controller.py --config_path ./configs/test/crossentropy.yml --precision fp16 